# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Subramanyam Molleti
tagline:          ''
url:              http://subramanyammolleti.github.io
paginate:         1
baseurl:          ''
paginate:         5

# About/contact
author:
  name:           Subramanyam Molleti
  url:            https://twitter.com/_MSubramanyam
  email:          subbumolleti002@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/subramanyammolleti/subramanyammolleti.github.io

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'
