# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Subramanyam Molleti
tagline:          ''
description:	  'Personal Blog of <a href="http://subramanyammolleti.github.io/about/">Subramanyam Molleti</a> who is a Software Engineer by Profession he loves Linux, Java, Javascript and Algorithms. Apart from these he likes Food and Travelling. Catch him at <a href="https://twitter.com/_MSubramanyam" target="_blank">@_MSubramanyam</a>.'
url:              http://subramanyammolleti.github.io
baseurl:          ''
paginate:         5

# About/contact
author:
  name:           Subramanyam Molleti
  url:            https://twitter.com/_MSubramanyam
  email:          subbumolleti002@gmail.com

# Custom vars
version:          1.0.0

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'
